name: Autenticacion AZURE
run-name: Autenticacion Service Principal

on: workflow_dispatch

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        auth-type: IDENTITY
        creds: ${{ secrets.AZURE_CREDENTIANS }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
