name: Publicar imagen docker
run-name: Publicar image docker

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-buildx-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username:${{secrets.USERNAME}}
          password:${{secrets.PASSWORD}}

      - name: Login to Github Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{secrets.PASSWORD_TOKEN}}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: | #
            eulalionava/practica_7.1:latest 
            ghcr.io/eulalionava/practica_7.1:latest 